BookList = ["BookID", 22, "BookTitle", "Think and grow rich", "BookPrice", 25, "BookAuthor", "Richard"]
print(BookList)
print(type(BookList))
print(len(BookList))
for i in (BookList):
    print(i)
print(BookList[6])
print(BookList[5])
print(BookList[7])
print(BookList[0])
print(type(BookList[6]))
print(type(BookList[4]))
BookList.append("Publisher")
print(BookList)
BookList.insert(3, "977")
print(BookList)
BookList.remove("BookPrice")
print(BookList)
BookList.pop(1)
print(BookList)
